/*
 * The MIT License
 *
 * Copyright 2014 MG Enterprises Consulting LLC.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

package org.mgenterprises.openbooks.views.configuration;

import java.lang.reflect.Field;
import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTextField;
import org.mgenterprises.openbooks.OpenbooksCore;
import org.mgenterprises.openbooks.configuration.ConfigurationManager;
import org.mgenterprises.openbooks.printing.InvoiceRenderer;
import org.mgenterprises.openbooks.views.ViewChangeListener;

/**
 *
 * @author Manuel Gauto
 */
public class ConfigurationPanel extends javax.swing.JPanel implements ViewChangeListener{
    private ConfigurationManager configurationManager;

    /**
     * Creates new form ConfigurationPanel
     */
    public ConfigurationPanel(ConfigurationManager configurationManager) {
        this.configurationManager = configurationManager;
        initComponents();
        loadCurrentData();
    }
    
    private void loadCurrentData() {
        Class clazz = this.getClass();
        Field[] fields = clazz.getFields();
        for(Field field: fields) {
            if(field.getClass().getName().equals(JTextField.class.getName())) {
                try {
                    JTextField textField = (JTextField) field.get(this);
                    textField.setText(configurationManager.getValue(field.getName().replace("Field", "")));
                } catch (IllegalArgumentException ex) {
                    Logger.getLogger(ConfigurationPanel.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                    Logger.getLogger(ConfigurationPanel.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        smtpServerLabel = new javax.swing.JLabel();
        smtpServerField = new javax.swing.JTextField();
        smtpPortLabel = new javax.swing.JLabel();
        smtpPortField = new javax.swing.JTextField();
        smtpUsernameLabel = new javax.swing.JLabel();
        smtpUsernameField = new javax.swing.JTextField();
        smtpPasswordLabel = new javax.swing.JLabel();
        encryptionLabel = new javax.swing.JLabel();
        encryptionComboBox = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        smtpPasswordField = new javax.swing.JPasswordField();

        setMinimumSize(new java.awt.Dimension(650, 650));

        smtpServerLabel.setText("SMTP Server");

        smtpServerField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smtpServerFieldActionPerformed(evt);
            }
        });

        smtpPortLabel.setText("SMTP Port");

        smtpPortField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smtpPortFieldActionPerformed(evt);
            }
        });

        smtpUsernameLabel.setText("SMTP Username");

        smtpUsernameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smtpUsernameFieldActionPerformed(evt);
            }
        });

        smtpPasswordLabel.setText("SMTP Password");

        encryptionLabel.setText("Encryption");

        encryptionComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "NONE", "SSL", "TLS" }));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jLabel1.setText("Email Content");

        smtpPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smtpPasswordFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(smtpServerLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(smtpServerField, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(smtpPortLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(smtpPortField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(encryptionLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(encryptionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(smtpUsernameLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(smtpUsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(smtpPasswordLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(smtpPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 45, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(smtpServerLabel)
                    .addComponent(smtpServerField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(smtpPortLabel)
                    .addComponent(smtpPortField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(smtpUsernameLabel)
                    .addComponent(smtpUsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(smtpPasswordLabel)
                    .addComponent(smtpPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(encryptionLabel)
                    .addComponent(encryptionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Email", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void smtpServerFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smtpServerFieldActionPerformed
        configurationManager.put("smtpServer", smtpServerField.getText());
    }//GEN-LAST:event_smtpServerFieldActionPerformed

    private void smtpPortFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smtpPortFieldActionPerformed
        configurationManager.put("smtpPort", smtpPortField.getText());
    }//GEN-LAST:event_smtpPortFieldActionPerformed

    private void smtpUsernameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smtpUsernameFieldActionPerformed
        configurationManager.put("smtpUsername", smtpUsernameField.getText());
    }//GEN-LAST:event_smtpUsernameFieldActionPerformed

    private void smtpPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smtpPasswordFieldActionPerformed
        configurationManager.put("smtpPassword", String.valueOf(smtpPasswordField.getPassword()));
    }//GEN-LAST:event_smtpPasswordFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox encryptionComboBox;
    private javax.swing.JLabel encryptionLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JPasswordField smtpPasswordField;
    private javax.swing.JLabel smtpPasswordLabel;
    private javax.swing.JTextField smtpPortField;
    private javax.swing.JLabel smtpPortLabel;
    private javax.swing.JTextField smtpServerField;
    private javax.swing.JLabel smtpServerLabel;
    private javax.swing.JTextField smtpUsernameField;
    private javax.swing.JLabel smtpUsernameLabel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void onSwitchTo(Object object) {
        loadCurrentData();
    }

    @Override
    public void onSwitchFrom() {
    }
}
